### ISSUE TITLE
Replace server side session with JWT tokens to support HA setups

### ISSUE THREAD

**Issue by mugnox** [gessnerfl/rabbitmq-queue-management#31]
We have an HA proxy in front. This causing White Label errors, every time when we try to re-queue a message. It's something with the session to the HA proxy, which is not keeping the connection active, until the operation is done.

**Comment by gessnerfl** [comment]
@mugnox This issue is caused by the HA setup. Currently there is no cluster support for this tool. This means if you run multiple instances the session state is not shared between the instances. I will fix this by moving the state to the client using cookies.
When no authentication is active there is also the issue that session management and csrf protection is still active. This will also be fixed with this change.

**Comment by gessnerfl** [comment]
Feature is provided with release 1.0.0. Please note that starting form version 0.7.0 Java 11 is required.
